changelog:
  exclude:
    labels:
      - ignore-for-release
      - dependencies
    authors:
      - dependabot
  categories:
    - title: 🚀 Features
      labels:
        - feature
        - enhancement
        - feat
    - title: 🐛 Bug Fixes
      labels:
        - bug
        - fix
        - bugfix
    - title: 📚 Documentation
      labels:
        - documentation
        - docs
    - title: 🔧 Maintenance
      labels:
        - maintenance
        - chore
        - refactor
    - title: 🔒 Security
      labels:
        - security
    - title: ⚡ Performance
      labels:
        - performance
        - perf
    - title: 🧪 Testing
      labels:
        - test
        - testing
    - title: 📦 Dependencies
      labels:
        - dependencies
        - deps
    - title: Other Changes
      labels:
        - "*"
