name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test-bun:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        bun-version: ['1.2', 'latest']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun ${{ matrix.bun-version }}
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ matrix.bun-version }}

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Lint code
        run: bun run lint

      - name: Run tests
        run: bun test

      - name: Build distribution
        run: bun run build

  check-deno:
    runs-on: ubuntu-latest
    needs: [test-bun]  # Need build artifacts first

    strategy:
      matrix:
        deno-version: ['1.40', '1.42', '1.44', '1.46', 'v1.x']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Deno ${{ matrix.deno-version }}
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}

      - name: Setup Bun (for building)
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.2'

      - name: Install dependencies and build
        run: |
          bun install --frozen-lockfile
          bun run build

      - name: Test built package compatibility
        run: deno run --allow-read --allow-run scripts/test-compatibility.mjs

  check-node:
    runs-on: ubuntu-latest
    needs: [test-bun]  # Need build artifacts first

    strategy:
      matrix:
        node-version: [18, 20, 22, 24]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup Bun (for building)
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.2'

      - name: Install dependencies and build
        run: |
          bun install --frozen-lockfile
          bun run build

      - name: Test built package compatibility
        run: node scripts/test-compatibility.mjs

  build-artifacts:
    runs-on: ubuntu-latest
    needs: [test-bun, check-deno, check-node]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.2'

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build distribution
        run: bun run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist/
          retention-days: 7
